### ISSUE TITLE
CorrMM images and kernel must have the same stack size

### ISSUE THREAD

**Issue by nassarofficial** [Kadenze/siamese_net#2]
Hello,
When I try to train my own dataset, after training I try to run the notebook, and at "Visualize the output of the network at any layer" step, I also get:
"ValueError: CorrMM images and kernel must have the same stack size"
I checked my resolution size, and made sure its 50, in all files. But still I get the error.

**Comment by pkmital** [comment]
That sounds like the implementation being used.  Maybe a library issue w/ Theano/Lasagne?  I haven't used the library in awhile but I'd check on their issues/closed issues for similar issues.
