### ISSUE TITLE
Usage of train set during performance evaluation

### ISSUE THREAD

**Issue by suryafyi** [Kadenze/siamese_net#5]
Hi @pkmital. In Line 2258 of siamese_net.py,
`for split in ['train', 'valid', 'test']:`
The pairs in the training set seems to be used to measure the performance of the trained model. Is this intentional? Aren't one supposed to not include the training set to evaluate the model? Or is it a special case in Siamese Networks?

**Comment by pkmital** [comment]
This part of the code is measuring the final performance of each dataset split, and is not used for training the model.  One would hope these each perform similarly, otherwise if they are different, then the model is likely over/underfitting.
